export const CHANGE_TOP_BANNERS = "recommend/CHANGE_TOP_BANNERS";
export const CHANGE_HOT_RECOMMEND = "recommend/CHANGE_HOT_RECOMMEND";
export const CHANGE_NEW_ALBUM = "recommend/CHANGE_NEW_ALBUM";

export const CHANGE_RANKINGLIST1="recommend/CHANGE_RANKINGLIST1";
export const CHANGE_RANKINGLIST2="recommend/CHANGE_RANKINGLIST2";
export const CHANGE_RANKINGLIST3="recommend/CHANGE_RANKINGLIST3";